Repository hmcts/hmc-hmi-outbound-adapter, pull requests merged in 2021-12, with the labels that each got.

#71 CCD-2312: Temporarily disable Fortify Scan in nightly build
  Jenkinsfile_nightly
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-71

#72 update log4j
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-72

#73 CCD-2351: Update log4j version to 2.16.0
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-73

#74 CCD-2374: Update log4j version to 2.17.0
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-74
