Repository hmcts/hmc-hmi-outbound-adapter, pull requests merged in 2021-07, with the labels that each got.

#27 HMAN-7 HMAN-18 read messages off a queue
  README.md
  build.gradle
  charts/hmc-hmi-outbound-adapter/Chart.yaml
  charts/hmc-hmi-outbound-adapter/values.preview.template.yaml
  charts/hmc-hmi-outbound-adapter/values.yaml
  config/owasp/suppressions.xml
  queue-writer-util/.gitignore
  queue-writer-util/README.md
  queue-writer-util/build.gradle
  queue-writer-util/gradle/wrapper/gradle-wrapper.jar
  queue-writer-util/gradle/wrapper/gradle-wrapper.properties
  queue-writer-util/gradlew
  queue-writer-util/gradlew.bat
  queue-writer-util/src/main/java/queue/QueueWriter.java
  src/functionalTest/java/uk/gov/hmcts/reform/hmc/hmi/befta/EmptySmokeTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageProcessorIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/GetWelcomeTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/repository/FutureHearingRepositoryIT.java
  src/integrationTest/resources/application-itest.yaml
  src/main/java/uk/gov/hmcts/reform/hmc/Application.java
  src/main/java/uk/gov/hmcts/reform/hmc/ApplicationParams.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageProcessor.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageReceiverConfiguration.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageType.java
  src/main/java/uk/gov/hmcts/reform/hmc/errorhandling/DeadLetterService.java
  src/main/java/uk/gov/hmcts/reform/hmc/errorhandling/MalformedMessageException.java
  src/main/java/uk/gov/hmcts/reform/hmc/errorhandling/ServiceBusMessageErrorHandler.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/ApplicationParamsTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/client/featurehearing/DeadLetterServiceTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/client/featurehearing/ServiceBusMessageErrorHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/config/MessageProcessorTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-27

#53 Nightly ccd 1565
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-53

#54 fix for CVE-2021-27568
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-54

#56 cve fixes
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-56

#55 CCD-1600 : Fortify Scan implementation for HMI Outbound Adapter
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-55
