Repository hmcts/hmc-hmi-outbound-adapter, pull requests merged in 2021-11, with the labels that each got.

#64 CCD-2124: Address CVE-2021-42340
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-64

#66 CCD-2145: Address CVE-2021-22096
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-66

#67 Update Jenkinsfile_CNP sync branches
  Jenkinsfile_CNP
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-67

#69 Remove temp file
  src/main/java/uk/gov/hmcts/reform/hmc/controllers/TempController.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-69

#68 CCD-2123: Address CVE-2021-37136 and CVE-2021-37137
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-68
