Repository hmcts/hmc-hmi-outbound-adapter, pull requests merged in 2022-06, with the labels that each got.

#108 HMAN-255 - increase test coverage for outbound microservice
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageReceiverConfiguration.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-108

#104 Update azure-messaging-servicebus to latest
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-104

#111 CCD-3334 RPO Suppression added for CVE-2022-22978
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-111

#109 CCD-3281: Add ARGs for builder stage paths to Dockerfile
  Dockerfile
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-109

#112 CCD-3387 Remove CVE Suppress Until Date from All Services
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-112

#113 CCD-3248 Monthly Review of All Security Flags - Commented out all sup…
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-113

#115 CCD-3248 Monthly Review of All Security Flags - All Suppressions comm…
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-115

#116 Log HTTP code to help debug FH errors
  src/main/java/uk/gov/hmcts/reform/hmc/client/futurehearing/FutureHearingErrorDecoder.java
  src/test/java/uk/gov/hmcts/reform/hmc/client/featurehearing/FutureHearingErrorDecoderTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-116

#117 Add some more logging for failed HMI requests
  src/main/java/uk/gov/hmcts/reform/hmc/client/futurehearing/FutureHearingErrorDecoder.java
  src/test/java/uk/gov/hmcts/reform/hmc/client/featurehearing/FutureHearingErrorDecoderTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-117
