Repository hmcts/hmc-hmi-outbound-adapter, pull requests merged in 2022-02, with the labels that each got.

#77 CCD-2543: Ignore Fortify scan results
  build.gradle
  config/fortify-client.properties
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-77

#78 CCD-2594: Suppress CVE pending investigation
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-78

#79 CVE fixes
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-79

#81 update heml version
  charts/hmc-hmi-outbound-adapter/Chart.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-81
