Repository hmcts/hmc-hmi-outbound-adapter, pull requests merged in 2022-12, with the labels that each got.

#149 CCD-4043 Fasterxml Jackson Upgrade
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-149

#150 HMAN-492 CVE-2021-37533 Suppression
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-150

#151 HMAN-495 Upgrade base charts for Jenkins enhancements - bumped java v…
  charts/hmc-hmi-outbound-adapter/Chart.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-151

#148 CCD-4050: Fix Jenkins pipeline warnings
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-148

#153 HMAN-497 CVE-2022-41881 Suppression
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-153

#154 CVE suppression added
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-154
