Repository hmcts/hmc-hmi-outbound-adapter, pull requests merged in 2022-05, with the labels that each got.

#102 CVE-2022-24823 : hmc-hmi-outbound-adapter fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-102

#103 suppression of CVE-2016-1000027 and until date extension for current …
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-103

#105 suppression of CVE-2022-29885
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-105
