Repository hmcts/hmc-hmi-outbound-adapter, pull requests merged in 2022-11, with the labels that each got.

#139 HMAN-423 HMAN-439 Suppressions
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-139

#140 HMAN-454 CVE-2022-31690, CVE-2022-31690 HMAN-455 CVE-2022-42252 Suppr…
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-140

#126 HMAN-348
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/hmc/config/QueueClientConfig.java
  src/main/java/uk/gov/hmcts/reform/hmc/repository/DefaultFutureHearingRepository.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/MessageProcessor.java
  src/main/resources/application.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-126

#141 HMAN-423, HMAN-434
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-141

#142 HMAN-455,HMAN-454: Tomcat and Spring Security
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-142

#145 Merge of branch HMAN-441 and master
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderConfiguration.java
  src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
  src/main/java/uk/gov/hmcts/reform/hmc/errorhandling/ServiceBusMessageErrorHandler.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/MessageProcessor.java
  src/test/java/uk/gov/hmcts/reform/hmc/client/featurehearing/ServiceBusMessageErrorHandlerTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-145

#146 Fix hmc-hmi-outbound-adapter CVEs
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-146
