Repository hmcts/hmc-hmi-outbound-adapter, pull requests merged in 2022-04, with the labels that each got.

#85 HMAN-137 - Queue sync responses from HMI
  build.gradle
  charts/hmc-hmi-outbound-adapter/Chart.yaml
  charts/hmc-hmi-outbound-adapter/values.preview.template.yaml
  charts/hmc-hmi-outbound-adapter/values.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/WiremockFixtures.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageProcessorIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/repository/FutureHearingRepositoryIT.java
  src/integrationTest/resources/application-itest.yaml
  src/main/java/uk/gov/hmcts/reform/hmc/ApplicationParams.java
  src/main/java/uk/gov/hmcts/reform/hmc/client/futurehearing/ErrorDetails.java
  src/main/java/uk/gov/hmcts/reform/hmc/client/futurehearing/FutureHearingErrorDecoder.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageReceiverConfiguration.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderConfiguration.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/SyncMessage.java
  src/main/java/uk/gov/hmcts/reform/hmc/errorhandling/BadFutureHearingRequestException.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/MessageProcessor.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/ApplicationParamsTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/client/featurehearing/FutureHearingErrorDecoderTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/config/MessageProcessorTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-85

#86 HMAN-141 update DateTimeFormat to yyyy-MM-dd'T'HH:mm:ssXXX
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/WiremockFixtures.java
  src/main/java/uk/gov/hmcts/reform/hmc/client/futurehearing/HearingManagementInterfaceRequestInterceptor.java
  src/test/java/uk/gov/hmcts/reform/hmc/client/featurehearing/HearingManagementInterfaceRequestInterceptorTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-86

#87 Bump Spring Framework to 5.3.18
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-87

#89 jackson.version update for CVE-2020-36518
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-89

#91 New Dates
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-91
