Repository hmcts/hmc-hmi-outbound-adapter, pull requests merged in 2023-01, with the labels that each got.

#155 Hman 500 CVE 2021 4277 suppression
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-155

#152 HMAN-494 Add suppressCves task
  .github/workflows/dependency-check.yml
  build.gradle
  config/owasp/suppressions.xml
  gradle/suppress.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-152

#157 HMAN-502 Bump rse-gradle-java-plugin version
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-157

#158 Update Chart.yaml
  charts/hmc-hmi-outbound-adapter/Chart.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-158
