Repository hmcts/hmc-hmi-outbound-adapter, pull requests merged in 2023-05, with the labels that each got.

#169 HMAN-530- CVE-2023-20861
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-169

#173 HMAN-539
  src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
  src/main/java/uk/gov/hmcts/reform/hmc/errorhandling/ServiceBusMessageErrorHandler.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/MessageProcessor.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-173

#175 HMAN-541 : bumped version of jetty and removed suppressions
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-175

#176 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-176

#177 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-177
