Repository hmcts/hmc-hmi-outbound-adapter, pull requests merged in 2023-10, with the labels that each got.

#185 CCD-4845: rennovate config
  .dependabot/config.yml
  .github/renovate.json
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-185

#188 HMAN-586 : review dynatrace logging statements
  src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-188

#191 Ccd 4949
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-191
