Repository hmcts/hmc-hmi-outbound-adapter, pull requests merged in 2023-11, with the labels that each got.

#192 CCD-4771 : Fix CVE-2023-35116
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-192

#193 CCD-4994 : Fix-CVE-2023-36478
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-193

#194 HMAN-602 : Add retries to manifest-create
  acb.tpl.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-194

#195 HMAN-602 : Add retries to all acb.tpl.yaml entries
  acb.tpl.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-195

#197 CCD-5066 : Fix broken master pipeline due to CVE clash between DBs
  .github/workflows/dependency-check.yml
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-197

#196 Remove keep:true acb config
  acb.tpl.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-196
