Repository hmcts/hmc-hmi-outbound-adapter, pull requests merged in 2024-04, with the labels that each got.

#213 HMAN-659 Remove CVE-2023-35116 suppression
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-213

#209 HMAN-658- Restore logging Defaults
  Dockerfile
  bin/functionalTest/DummyTest.xml
  bin/functionalTest/features/F-000/F-000.feature
  bin/functionalTest/features/F-000/S-000.td.json
  bin/integrationTest/application-itest.yaml
  build.gradle
  charts/hmc-hmi-outbound-adapter/Chart.yaml
  charts/hmc-hmi-outbound-adapter/values.preview.template.yaml
  charts/hmc-hmi-outbound-adapter/values.yaml
  lib/applicationinsights.json
  src/main/java/uk/gov/hmcts/reform/hmc/AppInsights.java
  src/test/java/uk/gov/hmcts/reform/hmc/AppInsightsTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-209

#215 HMAN-679 fix CVE-2023-44487
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-215

#216 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-216

#218 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-218

#206 Fix CVE-33202 : Update to SpringBoot v3
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/resources/features/F-000/S-000.td.json
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/BaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/WiremockFixtures.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/OpenApiConfigurationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/repository/FutureHearingRepositoryIT.java
  src/main/java/uk/gov/hmcts/reform/hmc/AppInsights.java
  src/main/java/uk/gov/hmcts/reform/hmc/ApplicationParams.java
  src/main/java/uk/gov/hmcts/reform/hmc/client/futurehearing/FutureHearingApiClientConfig.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageReceiverConfiguration.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/OpenApiConfiguration.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/SwaggerConfiguration.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/hmc/AppInsightsTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-hmi-outbound-adapter-pr-206
